### ISSUE TITLE
Example Django app

### ISSUE THREAD

**Issue by rohanmandhanya** [chunky-monkeys/keycloak-client#50]
while testing the Django app getting en error-
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/rohan/opt/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/rohan/opt/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rohan/opt/anaconda3/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/rohan/opt/anaconda3/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    handler = self.get_handler(*args, **options)
  File "/Users/rohan/opt/anaconda3/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/Users/rohan/opt/anaconda3/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/Users/rohan/opt/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 45, in get_internal_wsgi_application
    return import_string(app_path)
  File "/Users/rohan/opt/anaconda3/lib/python3.7/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/Users/rohan/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/rohan/PerceptiLabs/django-app/mysite/wsgi.py", line 17, in <module>
    application = get_wsgi_application()
  File "/Users/rohan/opt/anaconda3/lib/python3.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/Users/rohan/opt/anaconda3/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 127, in __init__
    self.load_middleware()
  File "/Users/rohan/opt/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 37, in load_middleware
    mw_instance = middleware(handler)
  File "/Users/rohan/opt/anaconda3/lib/python3.7/site-packages/keycloak/extensions/django.py", line 13, in __init__
    self.kc = Client(self.callback_uri)
  File "/Users/rohan/opt/anaconda3/lib/python3.7/site-packages/keycloak/extensions/django.py", line 21, in callback_uri
    return settings.KEYCLOAK_CALLBACK_URI
  File "/Users/rohan/opt/anaconda3/lib/python3.7/site-packages/django/conf/__init__.py", line 77, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'KEYCLOAK_CALLBACK_URI'

**Comment by akhilputhiry** [comment]
See the examples folder

You need to add 3 keys in settings file.
KEYCLOAK_CALLBACK_URL
KEYCLOAK_REDIRECT_URI
KEYCLOAK_LOGOUT_URI

**Comment by akhilputhiry** [comment]
I am closing this thread since there is no response.
