### ISSUE TITLE
Installing Extensions

### ISSUE THREAD

**Issue by MxLinux** [chunky-monkeys/keycloak-client#56]
**When installing**

```
(.env) debian@auth:~/flask-test$ pip install keycloak[extensions]
Requirement already satisfied: keycloak[extensions] in ./.env/lib/python3.7/site-packages (1.6.0)
WARNING: keycloak 1.6.0 does not provide the extra 'extensions'
```

**When running**

```
(.env) debian@auth:~/flask-test$ flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/home/debian/flask-test/.env/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/debian/flask-test/app.py", line 4, in <module>
    from keycloak.extensions.flask import AuthenticationMiddleware
ModuleNotFoundError: No module named 'keycloak.extensions'
```

Has something changed with installation steps? Maybe the imports are just different? I'm using [this](https://keycloak-client.readthedocs.io/en/latest/extensions/flask.html) code from the documentation.

**Comment by akhilputhiry** [comment]
Hi @MxLinux looks like its picking up `1.6.0` where as the latest version is `3.0.0`. Could you please try disabling cache

**Comment by akhilputhiry** [comment]
I hope the issue is resolved. Please feel free to reopen if you are still facing issues.
