### ISSUE TITLE
Trying to access the /logout path when logged out gives error

### ISSUE THREAD

**Issue by ybinnenwegin2ip** [chunky-monkeys/keycloak-client#57]
The Starlette implementation is used (via FastAPI).

When a user has been logged out and the user tries to access the `/logout` path again an internal server error is thrown:

```python
INFO:     127.0.0.1:45870 - "GET /logout HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/b1nny/virtualenvs/PROJECT/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 391, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/b1nny/virtualenvs/PROJECT/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/b1nny/virtualenvs/PROJECT/lib/python3.9/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/home/b1nny/virtualenvs/PROJECT/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/b1nny/virtualenvs/PROJECT/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/b1nny/virtualenvs/PROJECT/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/b1nny/virtualenvs/PROJECT/lib/python3.9/site-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/b1nny/virtualenvs/PROJECT/lib/python3.9/site-packages/keycloak-3.0.1rc1.post3+g3bdf7ef-py3.9.egg/keycloak/extensions/starlette.py", line 99, in __call__
    await Logout(scope, receive, send, kc=self.kc)
  File "/home/b1nny/virtualenvs/PROJECT/lib/python3.9/site-packages/starlette/endpoints.py", line 30, in dispatch
    response = await handler(request)
  File "/home/b1nny/virtualenvs/PROJECT/lib/python3.9/site-packages/keycloak-3.0.1rc1.post3+g3bdf7ef-py3.9.egg/keycloak/extensions/starlette.py", line 36, in get
    del request.session["user"]
KeyError: 'user'
```

I fixed this myself by moving the 'unauthorized requests' if-statement above the 'logout request' if-statement

**Comment by akhilputhiry** [comment]
@ybinnenwegin2ip Could you try this against the master branch. I have pushed some fixes. Let me know if its happening again in the master branch

**Comment by ybinnenwegin2ip** [comment]
> @ybinnenwegin2ip Could you try this against the master branch. I have pushed some fixes. Let me know if its happening again in the master branch

This solves the issue, thanks! :)
