### ISSUE TITLE
Singleton implementation ignores args / keywords

### ISSUE THREAD

**Issue by pelson** [chunky-monkeys/keycloak-client#60]
The Singleton implementation in utils ignores keywords, so you end up being able to do:

```
>>> import keycloak
>>> cli = keycloak.Client(blah=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "keycloak/utils.py", line 73, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'blah'
>>> cli = keycloak.Client()
>>> cli = keycloak.Client(blah=1)
```

I've seen this Singleton implementation elsewhere with the same problem, so I suspect it is not here by design. Just wanted to raise awareness. If you are OK with it, please feel free to close this issue.

**Comment by akhilputhiry** [comment]
This implementation do not expect any arguments. 
If you want to take arguments in to consideration, you will need something like 

```
class Singleton(type):
    """ metaclass for creating singleton classes """

    _instances: Dict = {}

    def __call__(cls, *args: Tuple, **kwargs: Dict) -> type:
        if args not in cls._instances:
            cls._instances[args] = super().__call__(*args, **kwargs)
        return cls._instances[args]
```

Note: I have not considered kwargs. For handling kwargs we will have to calculate hash of kwargs with something like 


```
import json
import hashlib

md5 = hashlib.md5()
encoded =  json.dumps(kwargs, sort_keys=True).encode()
md5.update(encoded)
md5.hexdigest()
```
